deploy:
  provider: heroku
  api_key:
    secure: XCx7nppWOVS/F6EsQRUC8eQEwjHKwFqzNpVT7KP2Z+iTnePai6u1S3UGQa77reQ8IOBZcCeVRShARZvI4/h/wXHG9OOHmYSFrxFwYi/5068kPBuWQ8KE6rgHQSDYeyT4LoHR4JuNaUafON6GYpeU1jB+KEgabb+8Z/BNKEu6ZWNpr1GGcxU1UfDWObGfKJTBqBp3aUVLhb0EalClCgNeLTZy5ekOVBIEd9uV9CEsQAFB06MC9VljI9mKcOAH52uR+bzESqNMXkkh79unhKPOcg9IQto2+Wkuo2CdeaoUDWs7DKMaEbuxRe7W/hQ+tjAgA8RPtCtS/jEIhBRb+AR7eJoyBSy2+XtTnJ3NqUZXAtt7D4E58lWFRhhgh47z2ZBAdPzxe42qtUGkt9rmyYx1fPMYVXO6s4kXMzODKyku+sQUDKyb4W9xeiNjp/a1OU2tdQUSvAHdKvqyiTL2WT0QkAVcllp4O/0Vb5BB/AEfOn90SFMiIEquG0tjUAxVuu5EuTyj96/Gvrxe91KVSAH1ttIYYbaRsJMtQYURQykILb58UmDNNpSFEMYZGlHuTfG9ftwlDXt9kf4TbfIxpx3VsyChxUFtxI4UK9kJSean43K3jedQ6HQeR3qKKbRuzngJCdG3gi4FANwz5vg7pghxhF7pQZ/w8Qp8A0xl36B3C90=
  app: warm-reef-54219
  on:
    repo: aleyesa/All-in-One-Product-Reviews
